# Generated by Django 5.2.6 on 2025-09-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('PARENT', 'Parent'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('ADMIN', 'Admin')], default='STUDENT', max_length=20),
        ),
    ]
